name: Update mono

on: [push]

jobs:

  build:

    runs-on: ubuntu-18.04

    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.EXP_TOKEN }}
          event-type: my-event
          repository: n0str/mono
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'